[project]
name = "pythonlearnproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
reamde = "README.md"
dependencies = [
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
    "tensorflow>=2.20.0",
]
